## Funzzy events file
# more details see: https://github.com/cristianoliveira/funzzy
#
# List here the tasks and the commands for this workflow
# then run `fzz` to start to work.

- name: build
  run:
    - npm run build
    - open dist/output.pdf
    - open ~/Applications/Alacritty.app
  run_on_init: true
  change: 'template/**'
  ignore: '**/node_modules/**'
